### ISSUE TITLE
multi-label classification / paperswithcode dataset

### ISSUE THREAD

**Issue by ghost** [voidful/TFkit#1]
Hi guys,

Hope you are all well !

I was wondering if **TFkit** can handle multi-label classification with 1560 labels.

More precisely, I would like to apply it to paperswithcode dataset where `labels` are called `tasks`.

Refs:
- [Repository](https://github.com/paperswithcode/paperswithcode-data) 
- [Dataset](https://paperswithcode.com/media/about/papers-with-abstracts.json.gz)

Thanks for any insights or inputs on that.

Cheers,
X

**Comment by voidful** [comment]
The previous version will have some problems with multi-label


I have fixed it in the new version, and put a related example by the way:
https://github.com/voidful/TFkit/blob/master/tfkit/demo_data/multi_label_classification.csv
To train multi-label, you need to convert the data into this format(The label in the target of the data will be separated by / )
`"Fifty-four patients had pancreas cancer, confirmed by resection or biopsy in all cases .",outcome/population`


But there are too many labels, so I’m not sure what the result will be.
- In order to cope with the imbalance of data, I have replaced BCELoss with BCEFOcalLoss, hope it will help
- You can also adjust the threshold here to find out the best precision and recall scores
https://github.com/voidful/TFkit/blob/f847f8a27112454049315ae0369a67c599a2a5ed/tfkit/classifier/mt_classifier.py#L77

**Comment by ghost** [comment]
Thanks for your reply !

I ll create a google colab, let's see what happens :-)

**Comment by ghost** [comment]
@voidful 

Here is the link to the **Google Colab**: 
https://colab.research.google.com/drive/1fo5LwWCebzp7WYfHNbM__9Av8gk7vADQ?usp=sharing

Do you have a Twitter or Telegram account if I need to ask you question that would pollute that thread ?

My **Telegram** is `deepocrates` or **Twitter** is https://twitter.com/paper2code

**Comment by ghost** [comment]
Hi Eric, @voidful 

I created a kaggle notebook instead
https://www.kaggle.com/lucmichalski/tfkit-multi-label-classifier-paperswithcode

So I prepared the dependencies, uploaded the dataset and transformed it into a csv file in the format you specified but how can I train it now ?

Cheers,
