### ISSUE TITLE
likelihood in parse_train_args()

### ISSUE THREAD

**Issue by russab0** [voidful/TFkit#3]
Hello!
I want to run the training with `model` argument like this `--model onebyone-pos`, as written in [BDG repo](https://github.com/voidful/BDG). But I get the following error:
`error: argument --model: invalid choice: 'onebyone-neg'`

I believe the problem is that possible choices are defined by the result of the function `list_all_model()` which does not return a specific type of the model ('_onebyone-pos_', '_onebyone-neg_', '_onebyone-both_'), but only a bare model '_onebyone_'. 

Why does that happen? It seems like there is some inconsistency in these two repositories. 
I think the easiest way to overcome this is to include additional argument `--likelihood` and rewrite readme for BDG.

**Comment by voidful** [comment]
Sorry for the outdated document, actually BDG repo is using an older version of TFKit. Therefore the BDG documents are different from TFKit. https://github.com/voidful/BDG/blob/main/requirement.txt

If you want to try it in the latest version of TFKit, you can use `--panel`.

The reason why I remove 'onebyone-neg' it‘s because it's more like an extension of onebyone generation, adding additional argument may not suit for all model, so I add a panel for model specify parameters.

**Comment by russab0** [comment]
@voidful, thank you for the reply! Could you clarify, how exactly I can use the `--panel` and specify _pos_ / _neg_ / _both_?

**Comment by voidful** [comment]
In the generation task, you may try like that:
`tfkit-train --model onebyone --config distilbert-base-multilingual-cased --train dataset_path --test dataset_path  --panel`
After model loading, you will see the input panel to specify pos / neg / both, you can set your parameter there.
```
handle_exceed, [default=start_slice]: 
likelihood, input an item in the list ['none', 'pos', 'neg', 'both'] :
reserved_len (number), [default=0]: 
```

I am looking for a better way to handle second-level parameters, maybe the next version will try a config.json file for all parameters.
