### ISSUE TITLE
Multi-task

### ISSUE THREAD

**Issue by surtex** [voidful/TFkit#5]
Hi,
Thank you for sharing! Could you explain what multitask approach do you use? For example, what architecture will be used if I apply bert for two classification tasks? Thanks in advance

**Comment by voidful** [comment]
Basically I follow the idea from [Multi-Task Deep Neural Networks for Natural Language Understanding](https://arxiv.org/abs/1901.11504)
For two classifier, they will share all BERT Layer, with a task specific linear layer.

Furthermore, In order to balance multi-classifier training. TFkit will follow this strategy to update:
![image](https://user-images.githubusercontent.com/10904842/120062902-f308ce00-c096-11eb-8549-296bfe0c4c8a.png)

**Comment by surtex** [comment]
Thank you!
