### ISSUE TITLE
Inconsistant meteor score with Huggingface's dataset api

### ISSUE THREAD

**Issue by zuujhyt** [voidful/TFkit#7]
Hello,
I try to compare the meteor score with the HF ```datasets``` library api and the one from your code.
But the meteor score is different.

HF:
```
from datasets import load_metric

predictions = ["It is a guide to action which ensures that the military always obeys the commands of the party"]
references = ["It is a guide to action that ensures that the military will forever heed Party commands"]

metric = load_metric('meteor')
results = metric.compute(predictions=predictions, references=references)
print(round(results["meteor"], 4))
>>0.7398
```
Your code:
```
import tfkit
from transformers import BartTokenizerFast

tokenizer = BartTokenizerFast.from_pretrained("facebook/bart-large")
evaluator = tfkit.utility.eval_metric.EvalMetric(tokenizer)

prediction = "It is a guide to action which ensures that the military always obeys the commands of the party"
reference = "It is a guide to action that ensures that the military will forever heed Party commands"
reference_list = [reference]
evaluator.add_record( 
    prediction,
    reference_list, 
    task='nlg')

for s in evaluator.cal_score('nlg'):
    print(s[1])    

>>{'Bleu_1': 0.6666666666296297, 'Bleu_2': 0.5601120335791714, 'Bleu_3': 0.4899973050007546, 'Bleu_4': 0.42085980692678454, 'METEOR': 0.44736091739438233, 'ROUGE_L': 0.6539961013645226, 'CIDEr': 0.0}
```
You can see the meteor score is different.
Did I do it right?
Thanks.

Edit:
I forgot to mention I removed ```ori_input``` in the  ```add_record``` method.
Also I remove ```metrics_to_omit=["METEOR"]```.
and may I ask why you omitted METEOR in the first place?

**Comment by voidful** [comment]
Meteor will be affected by statistical data and 4 parameters `alpha` `beta` `gamma` `delta`, resulting in different score from different source of meteor.

tfkit is the implementation of nlg-eval https://github.com/Maluuba/nlg-eval/blob/95af2dcce66feb0d1e2b01e1213eb90b52c9c330/nlgeval/pycocoevalcap/meteor/meteor.py

And huggingface uses nltk's implementation 
https://github.com/huggingface/datasets/blob/master/metrics/meteor/meteor.py

The difference in other token scores is probability because of preprocessing.

**Comment by zuujhyt** [comment]
okay, thanks!
